# Generated by Django 5.0.3 on 2024-03-14 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('road_name', models.CharField(default='', max_length=255)),
                ('contractor', models.CharField(default='', max_length=255)),
                ('workers', models.IntegerField()),
                ('job_time_arrived', models.TimeField()),
                ('job_time_finished', models.TimeField()),
                ('color', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=10)),
                ('line_type', models.CharField(max_length=10)),
                ('white_footage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('white_size', models.CharField(default='', max_length=50)),
                ('yellow_footage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yellow_size', models.CharField(default='', max_length=50)),
                ('dot_employee', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
