# Generated by Django 5.0.3 on 2024-03-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotMessage',
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
