# Generated by Django 5.0.3 on 2024-03-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_chatbotmessage_alter_dailyreport_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='workers',
            field=models.CharField(),
        ),
    ]
