# Generated by Django 5.0.3 on 2024-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dailyreport_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='white_footage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='white_size',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='yellow_footage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='yellow_size',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
