# Generated by Django 5.0.3 on 2024-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dailyreport_white_footage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='line_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
