# Generated by Django 5.0.3 on 2024-03-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dailyreport_line_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='line_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
