# Generated by Django 5.0.3 on 2024-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_dailyreport_white_footage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='white_line_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='yellow_line_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
