# Generated by Django 5.0.3 on 2024-03-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dailyreport_white_line_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='workers',
            field=models.CharField(default='', max_length=255),
        ),
    ]
