# Generated by Django 5.0.3 on 2024-04-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_dailyreport_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='arrows',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='onlys',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='railroad_crossing',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='stop_bars',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
