# Generated by Django 5.0.3 on 2024-04-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dailyreport_arrows_dailyreport_contract_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='rpm',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
