# Generated by Django 5.0.3 on 2024-04-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dailyreport_rpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='dot_employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
