# Generated by Django 5.0.3 on 2024-04-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_dailyreport_arrows_alter_dailyreport_onlys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='hand_work',
            field=models.BooleanField(default=False),
        ),
    ]
