# Generated by Django 5.0.3 on 2024-04-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_dailyreport_hand_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='user',
            new_name='user_id',
        ),
    ]
